name: Continuous Deployment Pipeline

on:
    push:
      branches: [ main ]
    pull_request:
      branches: [ main ]  

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          registry-url: 'https://npm.pkg.github.com'
          scope: '@heikkkk'
      - name: Automated Version Bump
        uses: 'phips28/gh-action-bump-version@master'
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}   
           
      - run: npm ci
      - run: npm publish
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
