name: Continuous Integration and Deployment Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
          registry-url: 'https://npm.pkg.github.com'
          scope: '@heikkkk' 

      - name: Install dependencies
        run: npm install

      - name: Lint (Failures Ignored)
        run: npm run lint || echo "Linting issues found, but ignoring..."
      
      - name: Format check with Prettier (Failures Ignored)
        run: npm run format -- --check || echo "Formatting issues detected, but ignoring..."

      - name: Run unit tests (Failures Ignored)
        run: npm run test:unit || echo "No unit tests found or other test errors, but continuing..."

      - name: Build
        run: npm run build

      - name: Setup .npmrc
        run: |
          echo "@heikkkk:registry=https://npm.pkg.github.com" >> .npmrc
          echo "//npm.pkg.github.com/:_authToken=${{ secrets.GITHUB_TOKEN }}" >> .npmrc

      - name: Publish to GitHub Packages
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
