name: E2E Tests

on:
  workflow_dispatch:
    inputs:
      PIPELINE_TYPE:
        description: 'Type of the pipeline'
        required: true
        default: 'multi-project-pipeline'

jobs:
  e2e-tests:
    runs-on: ubuntu-latest
    if: github.event.inputs.PIPELINE_TYPE == 'multi-project-pipeline'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'

      - name: Install dependencies
        run: npm install

      - name: Run Cypress E2E Tests
        run: npm run test:e2e:ci
